//English letter should e in lower case
const Map<String, String> ResourceMap = {
  'nepali language': 'नेपाली भाषा',
  'munshig': 'मुंशीजी',
  'categories': 'श्रेणीहरू',
  'income': 'आम्दानी ',
  'settings': 'सेटिंग्स',
  'expense': 'खर्च',
  'add': 'थप्नुहोस',
  'accounts': 'खाताहरू',
  'current balance': 'हालको ब्यालेन्स',
  'npr': 'रू',
  'new preference has been added': 'नयाँ प्राथमिकता थपिएको छ',
  'no changes has been made': 'कुनै परिवर्तन गरिएको छैन',
  'person': 'व्यक्ति',
  'profile': 'प्रोफाइल',
  'other': 'अन्य',
  'bank': 'बैंक',
  'cash': 'नगद',
  'account type': 'खाताको किसिम',
  'update': 'हेरफेर गर्नुहोस',
  'delete': 'मेटाउनुहोस ',
  'are you sure to delete this account?':
      'के तपाई यो खाता मेटाउन निश्चित हुनुहुन्छ?',
  'budget': 'बजेट',
  'expense projection': 'खर्चको अनुमान',
  'click to set budget': 'बजेट तय गर्न क्लिक गर्नुहोस',
  'set budget': 'बजेट तय गर्नुहोस',
  'update budget': 'बजेट संशोधन गर्नुहोस',
  'clear budget': 'बजेट खाली गर्नुहोस',
  'dashboard': 'गृहपृष्ठ',
  'expense amount': 'खर्च भएको रकम',
  'business income': 'ब्यबसायबाट भएको आय',
  'select your preferences': 'तपाईंको प्राथमिकता छान्नुहोस',
  'enter amount': 'रकम लेख्नुहोस',
  'source of income': 'आयको शिर्षक',
  'expense category': 'खर्चको शिर्षक',
  'select category': 'छान्नुहोस ',
  'date of expense': 'नगद बाहिरिएको मिति',
  'date of income': 'नगद भित्रीएको मिति',
  'add income': 'आम्दानी राख्नुहोस',
  'add expense': 'खर्च राख्नुहोस',
  'sorry, income for current month can only be added!':
      'माफ गर्नुहोस, चालु महिनाको मात्र आम्दानी रकम राख्न सकिन्छ!',
  'sorry, expense for current month can only be added!':
      'माफ गर्नुहोस, चालु महिनाको मात्र खर्च रकम राख्न सकिन्छ!',
  'select account': 'खाता चुन्नुहोस',
  'choose date': 'मिति रोज्नुहोस',
  'submit': 'स्वीकार गर्नुहोस',
  'description (optional)': 'विवरण (ऐच्छिक)',
  'please select category.': 'कृपया श्रेणी चुन्नुहोस',
  'please select account.': 'कृपया खाता चुन्नुहोस',
  'no transactions': 'कारोबार भएको छैन',
  'login as guest': 'दर्ता नगरी चलाउनुहोस',
  'register': 'दर्ता गर्नुहोस',
  'select your country': 'देश चयन गर्नुहोस',
  'warning': 'चेतावनी',
  'okay': 'ठिक छ',
  'cancel': 'रद्द गर्नुहोस',
  'add new category': 'नयाँ शिर्षक राख्नुहोस',
  'the data will be lost if you remove the app while using it as guest.':
      'दर्ता नगरी चलाउनुहुदा, यो एप्प हटाउनुभएको खण्डमा सबै डेटाहरु हराउन सक्छन।',
  'cannot delete! this account is linked with some transactions.':
      'हटाउन सकिएन! यो खाता कुनै कारोबारसँग सम्बन्धित छ।',
  'budget is not enough for the transaction. do you really want to add the transaction?':
      'यो कारोबारको लागी बजेट रकम अपुग भएको छ। के तपाई साचै यो कारोबार राख्न चाहनुहुन्छ ?',
  'Budget cannot be cleared as it in use.':
      'बजेट प्रयोग भैराखेको हुनाले , खाली  गर्न सकिएन।',
  'budget amount is not enough.': 'बजेट रकम पुगेन।',
  'transaction detail': 'कारोबारको विवरण',
  'date: ': 'मिति: ',
  'detail: ': 'विवरण: ',
  'amount: ': 'रकम: ',
  'transportation fare': 'ढुवानी',
  'more categories': 'थप श्रेणीहरू',
  'are you sure you want to delete this category? deleting the category will also clear all the records related to it.':
      ' के तपाई साचै यो श्रेणी हटाउन चाहनुहुन्छ ? हटाउनु भएको खण्डमा यो श्रेणीसँग सम्बन्धित सबै कारोबारहरूपनि मेटिने छन।',
  'update income': 'आम्दानी हेरफेर गर्नुहोस',
  'update expense': 'खर्च हेरफेर गर्नुहोस',
  'are you sure you want to delete this category?':
      'के तपाई साचै यो कारोबार हटाउन चाहनुहुन्छ ?',
  'cash outflow projection': 'नगद बाहिरिने प्रक्षेपण',
  'cash inflow projection': 'नगद भित्रीने प्रक्षेपण',
  'cash in': 'नगद भित्रीएको',
  'cash out': 'नगद बाहिरिएको',
  'gender': 'लिङ्ग',
  'edit': 'बदल्नु्',
  'email address': 'इ-मेल ठेगाना',
  'address': 'ठेगाना',
  'date of birth (B.S)': 'जन्म मिति (B.S)',
  'date of birth (A.D)': 'जन्म मिति (A.D)',
  'first name': 'नाम',
  'last name': 'थर',
  'phone number': 'फोन नम्बर',
  'date of birth': 'जन्म मिति',
  'report': 'रिपोर्ट',
  'choose your language': 'भाषा छान्नुहोस्',
  'nepali': 'नेपाली',
  'english': 'अंग्रेजी',
  'valid phone number must be added to continue':
      'अगाडि बढ्नका लागी मान्य फोन नम्बर राख्नुहोस',
  'skip': 'छोड्नुहोस्',
  'add your photo\nhere': 'तपाईंको फोटो यहाँ\nथप्नुहोस्',
  'error, image cannot be uploaded': 'फोटो अपलोड गर्न सकिएन ',
  'save': 'सम्हालेर राख्नुहोस ',
  'please restart your app': 'कृपया तपाईको एप्प पुन: सुरु गर्नुहोस्',
  'a.d date picker': 'ए.डि मिति रोज्नुहोस ',
  'b.s date Picker': 'बि.एस छोड्नुहोस्',
  'male': 'पुरुष',
  'female': 'महिला',
  'create account': 'खाता खोल्नुहोस ',
  'goat': 'बाख्रा पालन',
  'seed': 'वीउ',
  'vegetable': 'सागसब्जी',
  'poultry': 'कुखुरा पालन',
};
